# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  notification:
    secrets:
      - clickatell-user
      - clickatell-password
      - clickatell-api-id
    environment:
      - LANGUAGES=en
      - SMS_PROVIDER=clickatell
      - CLICKATELL_USER_PATH=/run/secrets/clickatell-user
      - CLICKATELL_PASSWORD_PATH=/run/secrets/clickatell-password
      - CLICKATELL_API_ID_PATH=/run/secrets/clickatell-api-id

  gateway:
    environment:
      - LANGUAGES=en

  workflow:
    environment:
      - LANGUAGES=en

secrets:
  clickatell-user:
    external: true
  clickatell-password:
    external: true
  clickatell-api-id:
    external: true
