version: '3.3'

services:
  # configure reverse proxy for public endpoints
  traefik:
    image: traefik
    ports:
      - '80:80'
      - '443:443'
      - '8090:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/acme.json:/acme.json
    configs:
      - source: traefik.{{ts}}
        target: /etc/traefik/traefik.toml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  register:
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: register.opencrvs-staging.jembi.org,opencrvs-staging.jembi.org'
        - 'traefik.frontend.redirect.regex=^https?://opencrvs-staging.jembi.org/(.*)'
        - 'traefik.frontend.redirect.replacement=https://register.opencrvs-staging.jembi.org/$${1}'
        - 'traefik.port=5000'
        - 'traefik.docker.network=opencrvs_default'

  performance:
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: performance.opencrvs-staging.jembi.org'
        - 'traefik.port=5000'
        - 'traefik.docker.network=opencrvs_default'
  login:
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: login.opencrvs-staging.jembi.org'
        - 'traefik.port=5000'
        - 'traefik.docker.network=opencrvs_default'

  auth:
    secrets:
      - jwt-public-key.{{ts}}
      - jwt-private-key.{{ts}}
    environment:
      - CERT_PRIVATE_KEY_PATH=/run/secrets/jwt-private-key.{{ts}}
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: auth.opencrvs-staging.jembi.org'
        - 'traefik.port=4040'
        - 'traefik.docker.network=opencrvs_default'

  user-mgnt:
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}

  notification:
    secrets:
      - clickatell-user
      - clickatell-password
      - clickatell-api-id
      - jwt-public-key.{{ts}}
    environment:
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}

  gateway:
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: gateway.opencrvs-staging.jembi.org'
        - 'traefik.port=7070'
        - 'traefik.docker.network=opencrvs_default'

  workflow:
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: workflow.opencrvs-staging.jembi.org'
        - 'traefik.port=5050'
        - 'traefik.docker.network=opencrvs_default'

  hearth:
    secrets:
      - jwt-public-key.{{ts}}

  openhim-console:
    configs:
      - source: openhim-console-conf.{{ts}}
        target: /usr/share/nginx/html/config/default.json

secrets:
  jwt-public-key.{{ts}}:
    external: true
  jwt-private-key.{{ts}}:
    external: true
  clickatell-user:
    external: true
  clickatell-password:
    external: true
  clickatell-api-id:
    external: true

configs:
  openhim-console-conf.{{ts}}:
    file: ./infrastructure/openhim-console-config.staging.json
  traefik.{{ts}}:
    file: ./infrastructure/traefik.toml
