groups:
  - name: alert.rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: 'critical'
        annotations:
          summary: 'Endpoint {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes.'

      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'Host out of memory (instance {{ $labels.instance }})'
          description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 90
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: 'Host out of disk space (instance {{ $labels.instance }})'
          description: "Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HostHighCpuLoad
        expr: (sum by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]))) > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'Host high CPU load (instance {{ $labels.instance }})'
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
