# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  notification:
    secrets:
      - infobip-gateway-endpoint
      - infobip-api-key
      - infobip-sender-id
    environment:
      - LANGUAGES=bn,en
      - SMS_PROVIDER=infobip
      - INFOBIP_GATEWAY_ENDPOINT_PATH=/run/secrets/infobip-gateway-endpoint
      - INFOBIP_API_KEY_PATH=/run/secrets/infobip-api-key
      - INFOBIP_SENDER_ID=/run/secrets/infobip-sender-id

  resources:
    secrets:
      - oisf-secret
    environment:
      - OISF_SECRET=/run/secrets/oisf-secret

  workflow:
    environment:
      - LANGUAGES=bn,en

  bgd-dhis2-mediator:
    image: jembi/ocrvs-bgd-dhis2-mediator
    secrets:
      - jwt-public-key.{{ts}}
      - openhim-user
      - openhim-password
    environment:
      - CERT_PUBLIC_KEY_PATH=/run/secrets/jwt-public-key.{{ts}}
      - AUTH_URL=http://auth:4040
      - FHIR_URL=http://openhim-core:5001/fhir
      - OPENHIM_USER_PATH=/run/secrets/openhim-user
      - OPENHIM_PASSWORD_PATH=/run/secrets/openhim-password
      - OPENHIM_URL=https://openhim-core:8080
      - TRUST_SELF_SIGNED=true
    deploy:
      replicas: 1
    networks:
      - overlay_net

secrets:
  infobip-gateway-endpoint:
    external: true
  infobip-api-key:
    external: true
  infobip-sender-id:
    external: true
  jwt-public-key.{{ts}}:
    external: true
  openhim-user:
    external: true
  openhim-password:
    external: true
  oisf-secret:
    external: true
