logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# This is used so we can comunicate with OpenHIM's API while it uses
# the default self-signed cert. This makes configuration easier and
# is ok because all communication takes place on a private docker
# swarm network.
insecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]

[api]

[ping]

[docker]
domain = "{{hostname}}"
swarmMode = true
exposedByDefault = false
watch = true

[acme]
email = "ryan@jembi.org"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
  main = "{{hostname}}"
  sans = [
    "register.{{hostname}}",
    "login.{{hostname}}",
    "auth.{{hostname}}",
    "gateway.{{hostname}}",
    "performance.{{hostname}}",
    "resources.{{hostname}}",
    "openhim-api.{{hostname}}",
    "api.{{hostname}}",
    "openhim.{{hostname}}",
    "styleguide.{{hostname}}",
  ]

[retry]

# Enable gzip compression
[http.middlewares]
  [http.middlewares.test-compress.compress]