apiVersion: v1
kind: Service
metadata:
  labels:
    app: documents
  name: documents
spec:
  ports:
    - port: 9050
      targetPort: 9050
  selector:
    app: documents
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: documents
  name: documents
spec:
  replicas: {{ .Values.dashboards.replicas }}
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
        - name: documents
          env:
            - name: COUNTRY_CONFIG_URL
              value: {{ .Values.countryconfigUrl }} # FIXME harcoded
            - name: NODE_ENV
              value: development
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: MINIO_HOST
              value: "{{ .Values.minioUrl }}"
            - name: MINIO_PORT
              value: "3535"
            - name: DOCUMENTS_PORT
              value: "4040"
          image: "opencrvs/ocrvs-documents:{{ .Values.image.tag }}"
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
          ports:
            - containerPort: 9050
              protocol: TCP
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key