apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: notification
spec:
  ports:
    - port: 2020
      targetPort: 2020
  selector:
    app: notification
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification
  name: notification
spec:
  replicas: {{ .Values.notification.replicas }}
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: "opencrvs/ocrvs-notification:{{ .Values.image.tag }}"
          env:
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: COUNTRY
              value: bgd
            - name: COUNTRY_CONFIG_URL
              value: {{ .Values.countryconfigUrl }} # FIXME: harcoded
            - name: MONGO_URL
              value: {{ .Values.mongoUrl }}/notification
            - name: HOST
              value: 0.0.0.0
          ports:
            - containerPort: 2020
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key