apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-mgnt
  name: user-mgnt
spec:
  ports:
    - port: 3030
      targetPort: 3030
  selector:
    app: user-mgnt
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-mgnt
  name: user-mgnt
spec:
  replicas: {{ .Values.userMgnt.replicas }}
  selector:
    matchLabels:
      app: user-mgnt
  template:
    metadata:
      labels:
        app: user-mgnt
    spec:
      containers:
        - name: user-mgnt
          image: "opencrvs/ocrvs-user-mgnt:{{ .Values.image.tag }}"
          env:
            - name: APPLICATION_CONFIG_URL
              value: {{ .Values.applicationConfigUrl }} # FIXME: harcoded/
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: FHIR_URL
              value: {{ .Values.fhirUrl }} # FIXME: harcoded
            - name: HOST
              value: 0.0.0.0
            - name: METRICS_URL
              value: {{ .Values.metricsUrl }} # FIXME: harcoded
            - name: MONGO_URL
              value: {{ .Values.mongoUrl }}/user-mgnt
            - name: NOTIFICATION_SERVICE_URL
              value: {{ .Values.notificationServiceUrl }}
            - name: DOCUMENTS_URL
              value: http://documents.opencrvs-services-dev.svc.cluster.local:9050
          ports:
            - containerPort: 3030
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key